# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77ad221e51051a5dbc4297936ccc1d786e01d3fe4db7b0d07b0d80d97cfef69cdeec2f4bdfc8b84cf6a59b5694a46160f58f69ad42df4f21459d5d32c2ce860c

test:
  secret_key_base: 084830fe1951b5ec8ff1473996d473d2c41a61a866412cd8003a14507f46d3c8e1dc9b107a6c6eb005a45a880d43d1aeb3add164f6fc6fbafa1d78afdaae43c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
